### PR TITLE
Fix issue with pylibmc binary mode never being set.

### PR DESCRIPTION
**Pull request by rogerhu**

### CODE REVIEW

**Comment by gusdan** [comment]
Good catch. But that is interesting Django doesn't support it in 1.7 as well.
https://github.com/django/django/blob/stable/1.7.x/django/core/cache/backends/memcached.py#L185
did you try that option? Any speed changing in case of using with ElasticCache?

**Comment by rogerhu** [comment]
I haven't benchmarked myself but there are several perf measurements that people have done in the past..

http://www.creapptives.com/post/46449295377/binary-protocol-benchmarks-for-memcached

**Comment by gusdan** [comment]
I was wondering why django comunity didn't set that flag. And i performed my own simple bacnhmarks and binary protocol works slowly for long strings (not numbers). I did simple test:
1. clone you repo
2. add it to virtual env
3. run django shell
4. perform 1000 reads for same key with value = '1'*1000

old version (no binary) takes 1.359 - 1.405s
new version (binary) takes 1.419 - 1.438s

i think it's common usecase for memcache: storing long string (html pages, pickle, jsons). and binary protocol does some otherhead here without pros of minimize transfering. 

So i'm going to reject your pull request unless you have some objections.

**Comment by robbyt** [comment]
Just a note about this, I've seen issues with pickled objects silently becoming corrupt when forcing memcached binary mode. It was a deep bug, and suggest you stay away from memcached binary mode w/ django.

**Comment by gusdan** [comment]
Thank you for update.

**Pull request closed without merging**
