### PR TITLE
Move pylibmc behaviors into sub behaviors key

### PR DESCRIPTION
**Pull request by adepue**
Related to https://github.com/gusdan/django-elasticache/issues/18.

@gusdan Any thoughts on this change?  

Also I would be willing to up the base supported version of django if you were interested given their deprecation/support schedule.

### CODE REVIEW

**Comment by asherf** [comment]
👍

**Comment by rebkwok** [comment]
@gusdan Any chance this will be merged soon? We are having the same issue with Django 1.11.

**Comment by gusdan** [comment]
guys sorry for delay. I just merged pull request, created new version 1.0.2 and pushed it it pypy.

@adepue thank you for pull request :+1:

**Comment by adepue** [comment]
Thanks for the merge!

**Comment by rebkwok** [comment]
Thanks!

**Pull request merged**
